# Generated by Django 6.0.5 on 2026-05-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Lưu trữ các thuộc tính linh hoạt của thư mục (VD: môn học, cấp học...)'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Thuộc tính được kế thừa hoặc chọn lúc tải lên'),
        ),
    ]
