# Generated by Django 6.0.5 on 2026-05-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_systemsetting_documentchunk_heading_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectoryPermission',
        ),
    ]
