# Generated by Django 6.0.5 on 2026-06-01 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_directorypermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_before', models.CharField(max_length=255)),
                ('title_after', models.CharField(max_length=255)),
                ('description_before', models.TextField(blank=True, null=True)),
                ('description_after', models.TextField(blank=True, null=True)),
                ('target_student_before', models.CharField(max_length=100)),
                ('target_student_after', models.CharField(max_length=100)),
                ('attributes_before', models.JSONField(blank=True, default=dict)),
                ('attributes_after', models.JSONField(blank=True, default=dict)),
                ('file_name_before', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name_after', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_histories', to='app.lessonplan')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
