# Generated by Django 6.0.5 on 2026-06-03 03:13

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lessonplanedithistory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_vector_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
