# Generated by Django 6.0.5 on 2026-06-17 04:37

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_otp_code_user_otp_created_at'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['status'], name='app_lessonp_status_c51db2_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='lp_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_preview'], name='lp_content_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
