# Generated by Django 6.0.5 on 2026-06-17 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_lessonplan_app_lessonp_status_c51db2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiNoteEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_before', models.TextField()),
                ('content_after', models.TextField()),
                ('change_type', models.CharField(default='MANUAL', max_length=50)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
