# Generated by Django 6.0.5 on 2026-06-27 07:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_wikinoteedithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='file_path',
            field=models.FileField(upload_to=app.models.get_upload_path),
        ),
    ]
