# Generated by Django 6.0.5 on 2026-07-03 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_lessonplan_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplanedithistory',
            name='review_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplanedithistory',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplanedithistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edit_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplanedithistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã chấp nhận'), ('REJECTED', 'Đã từ chối')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonplanedithistory',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
