# Generated by Django 6.0.5 on 2026-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_lessonplanedithistory_review_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplanedithistory',
            name='file_path_after',
            field=models.FileField(blank=True, null=True, upload_to='edit_histories/after/'),
        ),
        migrations.AddField(
            model_name='lessonplanedithistory',
            name='file_path_before',
            field=models.FileField(blank=True, null=True, upload_to='edit_histories/before/'),
        ),
    ]
