# Generated by Django 6.0.5 on 2026-07-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_lessonplanedithistory_file_path_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lessons', models.ManyToManyField(blank=True, related_name='concept_notes', to='app.lessonplan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
