# Generated by Django 6.0.5 on 2026-07-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_conceptnote'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE app_conceptnote ENABLE ROW LEVEL SECURITY;
            ALTER TABLE app_conceptnote_lessons ENABLE ROW LEVEL SECURITY;
            """,
            reverse_sql="""
            ALTER TABLE app_conceptnote DISABLE ROW LEVEL SECURITY;
            ALTER TABLE app_conceptnote_lessons DISABLE ROW LEVEL SECURITY;
            """
        ),
    ]
